remote_theme: pages-themes/leap-day@v0.2.0  
plugins:  
  - jekyll-remote-theme   # (if you already have a plugins list, add this)

title: "Mijn Nederlands"  
description: "Ik zal deze verdomde taal leren"  
